### ISSUE TITLE
To-do list for next major release

### ISSUE THREAD

**Issue by HDembinski** [resample-project/resample#94]
- [x] Estimate statistical uncertainty of p-value from permutation tests
- [x] Allow users to pass a target precision to the permutation test instead of asking for the number of bootstrap samples
- [x] Generic permutation test for user-defined test statistics
- [x] allow sample arguments in resample, bootstrap, etc.
- [x] Include USP test (see #89)
- [x] Document changes and write migration guide
- [x] Fix the iterative algorithm to find the required number of permutation samples for usp and same_population

As pointed out [in the Wikipedia](https://en.wikipedia.org/wiki/Resampling_(statistics)#Monte_Carlo_testing), we should give a confidence interval for the computed pvalue in permutation tests.

With this one could also implement an automatic mode, where the number of required permutations is determined automatically that is needed to determine with near certainty whether the pvalue is below or above a given threshold α.

The pvalue confidence interval can be added as another field to the PermutationResult class. In order to use the automatic mode, the user has to provide `alpha` instead of `size` when the test is called, so the option for the test should probably be called `size_or_alpha`.

**Comment by HDembinski** [comment]
@dsaxton Do you have thoughts on this?

**Comment by dsaxton** [comment]
@HDembinski I think this is a good idea in principle, but there is the downside that the confidence interval could be misinterpreted. If I understand correctly, this is essentially a c.i. on the "true" p-value that would be obtained from all possible results, but this does not translate into confidence that the conclusion is actually correct (which would have to account for uncertainty in the underlying sample, which can't be "simulated away").

Suppose for instance that the permutation space is small enough that we actually could enumerate all possibilities. Then we'd report a confidence interval that's a single point, but that could be seen as misleading.

I would say supporting it is probably better than not (and the "automatic" mode seems like a good idea too), but would want to make sure to document it well so people understand what the interval does and does not represent.

**Comment by HDembinski** [comment]
That all makes sense. I think it is generally useful to give the user some idea on how precise the resampled estimate is.

**Comment by HDembinski** [comment]
@dsaxton I think we are ready for the next release, I am now happy with the permutation tests and they are now well tested.

I would not call the next release 2.0, but 1.5, to indicate that there have been big changes wrt to 1.0.1. What do you think?

**Comment by dsaxton** [comment]
> @dsaxton I think we are ready for the next release, I am now happy with the permutation tests and they are now well tested.
> 
> I would not call the next release 2.0, but 1.5, to indicate that there have been big changes wrt to 1.0.1. What do you think?

That's fine, looks like there are already things milestoned for 1.6

**Comment by HDembinski** [comment]
@dsaxton Yes, I want to get a new release out ASAP, so I was thinking about other things that are planned and whether those can be implemented in a backward-compatible way or not. The idea is to get the breaking things done in this release and then keep things backward compatible.

**Comment by HDembinski** [comment]
I think the other open points in the list can be implemented in a backward compatible way and so I started to assign those to 1.6.

**Comment by HDembinski** [comment]
@dsaxton Maybe one other thing: I am considering to rename some of the tests in `permutation` to better match scipy
- pearson: pearsonr
- spearman: spearmanr

This is to reduce the ambiguity, `pearson` could refers to Pearson's chi2 test of independence or Pearson's correlation test.

**Comment by HDembinski** [comment]
We could also try to be super consistent and also rename `ttest` to `ttest_ind` and `anova` to `f_oneway`, but here the scipy names seem to be themselves to be historical artifacts.

**Comment by dsaxton** [comment]
> @dsaxton Maybe one other thing: I am considering to rename some of the tests in `permutation` to better match scipy
> 
> * pearson: pearsonr
> * spearman: spearmanr
> 
> This is to reduce the ambiguity, `pearson` could refer to Pearson's chi2 test of independence or Pearson's correlation test.

Makes sense

**Comment by HDembinski** [comment]
@dsaxton What do you think about removing the ks test altogether? 

One of the arguments for permutation based testing is that the p-value is often computed from asymptotic theory. But in case of the KS one can compute the distribution of the KS distance under the null for small samples exactly, and then use asymptotic theory only for large samples, see the scipy implementation:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html?highlight=ks#scipy.stats.ks_2samp

In this light, is there any benefit in offering the permutation-based KS test?

**Comment by dsaxton** [comment]
> @dsaxton What do you think about removing the ks test altogether?
> 
> One of the arguments for permutation based testing is that the p-value is often computed from asymptotic theory. But in case of the KS one can compute the distribution of the KS distance under the null for small samples exactly, and then use asymptotic theory only for large samples, see the scipy implementation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html?highlight=ks#scipy.stats.ks_2samp
> 
> In this light, is there any benefit in offering the permutation-based KS test?

That's interesting. I suppose a benefit would be that exact tests are usually more expensive to compute, so this would be a cheap way of approximating the same (which could be a significant savings for larger samples). Even if the utility is small, do you think the maintenance cost of having the functionality is higher? May not hurt just to keep it.

**Comment by HDembinski** [comment]
I am indeed concerned about the maintenance cost and about possible duplication. I am a big fan of minimalism and if some functionality is already included in scipy, which is a real foundational library (even though it has its various shortcomings), then we should remove it so that people do not get confused. SciPy uses the exact calculation for samples smaller than 10000 and uses the asymptotic formula for larger values. I don't know how fast that is, but the advantage of an exact calculation is that you do not have any uncertainty on the p-value. With the permutation tests, it is difficult to get accuracy at the level 0.001 (0.01 is cheap).

**Comment by HDembinski** [comment]
Scipy is orders of magnitude faster whether the sample is small or large.
```py
x = np.arange(10)
%timeit ks_2samp(x, x)
74.3 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

%timeit ks(x, x)
7.18 ms ± 286 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

x = np.arange(5000)

%timeit ks(x, x)
104 ms ± 431 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit ks_2samp(x, x)
424 µs ± 3.09 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

**Comment by HDembinski** [comment]
Looking further, the `mannwhiteneyu` is also implemented as an exact test for small samples in SciPy, so it can also be removed:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html#scipy.stats.mannwhitneyu

**Comment by HDembinski** [comment]
To document it for the release notes of 1.5, the following tests which remain in the package but gave wrong pvalues in 1.0.1 are:
- anova
- pearsonr
- spearmanr
- ttest
- kruskal

Which is - unfortunately - all of them. The problem was that we computed a two-sided test statistic, but did not take into account that the test statistic can then deviate positively and negatively from the resampled versions. This was not uncovered by the tests, because the old tests did not check the p-values against the scipy implementations.
